version: "3"
services:
  crud_app:
    container_name: crud_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings_DefaultConnection="Host=db;Database=postgres;Username=postgres;Password=postgres"
    networks:
      - dotnet-api-pipeline-main

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdatabase:/var/lib/postgresql/data
    networks:
      - dotnet-api-pipeline-main

volumes:
  pgdatabase:

networks:
  dotnet-api-pipeline-main:
    external:
      name: dotnet-api-pipeline-main